# Generated by Django 4.0.2 on 2022-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydiary',
            name='breakfastCarbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='breakfastFats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='breakfastProtein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='dinnerCarbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='dinnerFats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='dinnerProtein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='lunchCarbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='lunchFats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydiary',
            name='lunchProtein',
            field=models.IntegerField(default=0),
        ),
    ]
