# Generated by Django 3.2.12 on 2022-04-17 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthWebsite', '0002_dailydiary_breakfastcarbs_dailydiary_breakfastfats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('addressLine1', models.CharField(max_length=500)),
                ('addressLine2', models.CharField(max_length=500)),
                ('addressCity', models.CharField(max_length=500)),
                ('addressState', models.CharField(max_length=500)),
                ('addressZipCode', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
