# Generated by Django 4.0.3 on 2022-04-20 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthWebsite', '0003_addressinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydiary',
            name='attended_gym',
        ),
        migrations.RemoveField(
            model_name='dailydiary',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dailydiary',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='dailydiary',
            name='protein',
        ),
        migrations.CreateModel(
            name='TempDailyDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('breakfastProtein', models.IntegerField(default=0)),
                ('breakfastCarbs', models.IntegerField(default=0)),
                ('breakfastFats', models.IntegerField(default=0)),
                ('lunchProtein', models.IntegerField(default=0)),
                ('lunchCarbs', models.IntegerField(default=0)),
                ('lunchFats', models.IntegerField(default=0)),
                ('dinnerProtein', models.IntegerField(default=0)),
                ('dinnerCarbs', models.IntegerField(default=0)),
                ('dinnerFats', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('exercises', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HealthWebsite.exerciselist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
