# Generated by Django 3.2.12 on 2022-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthWebsite', '0007_remove_profile_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=750),
        ),
    ]
