# Generated by Django 4.0.2 on 2022-04-20 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthWebsite', '0010_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rejected',
            field=models.ManyToManyField(related_name='rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
